[package]
name = "chitra_os"
version = "0.1.0"
authors = ["Ailton Duarte <adidas.coyas@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.10.3"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"